#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.0.{build}
os: WMF 5
install:
  - ps: . .\AppVeyor\AppVeyorInstall.ps1

environment:
  MySecureVar:
    secure: 2miEAGV72ED32TvZbXUbQA== #This is secured
  MyNonSecureVar: NonSecure
  ModuleName: appVeyorDemo
#---------------------------------# 
#      build configuration        # 
#---------------------------------# 
build_script: 
  - ps: . .\AppVeyor\AppVeyorBuild.ps1

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 
test_script: 
  - ps: . .\AppVeyor\AppVeyorTest.ps1

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
deploy_script: 
  - ps: . .\AppVeyor\AppveyorDeploy.ps1